---
title: "Plots Type I & Power SVNP"
author: "Koch, J.M.B. (Michael)"
date: '2022-05-02'
output: html_document
---

```{r, echo=F}
knitr::opts_chunk$set(echo = F, message = F)
```

# Step1: Prepearations

```{r, message = F, warning = F}
# load packages outside of simulation
library(papaja)
library(patchwork)
#source required functions & parameters
source('~/OneDrive/ms/thesis/R/functions.R')
source('~/OneDrive/ms/thesis/R/parameters.R')
```

```{r}
# load results
resultsSVNP <- read.csv("~/1vs2StepBayesianRegSEM/output/resultsSVNP.csv", 
                        sep = " ", 
                        header = TRUE)
convSVNP <- read.csv("~/1vs2StepBayesianRegSEM/output/convSVNP.csv",
                     sep = " ",
                     header = TRUE)
```

## Post-process

```{r}
resultsSVNP <- 
  resultsSVNP %>% 
  arrange(sigma, N, cross, iteration) %>% 
  mutate(sigmaSqu = sigma^2,
         biasCrossMean_1 = abs(crossEstMean_1 - cross),
         biasCrossMean_2 = abs(crossEstMean_2 - 0),
         biasCrossMean_3 = abs(crossEstMean_3 - 0),
         biasCrossMean_4 = abs(crossEstMean_4 - 0),
         biasCrossMean_5 = abs(crossEstMean_5 - 0),
         biasCrossMean_6 = abs(crossEstMean_6 - cross) 
) 
  
```

# Step 2: Compute Type I error rate and Power

## Type I error rate

```{r, echo = F, include = F}
# For Tresholdvariables: 1 = nonZero, 0 = zero
# For CI variables: 0 = nonZero, 1 = zero
TypeISVNP <- 
 resultsSVNP %>% 
  select(
        isZeroTres0.10Mean_1:isZero50CI_6,
        cross,
        sigmaSqu,
        N, 
        pos,
        iteration,
        ) %>% 
  group_by(N, sigmaSqu, cross) %>% 
  summarise(typeITres0.15Mean_2 = mean(isZeroTres0.15Mean_2),
            typeITres0.15Mean_3 = mean(isZeroTres0.15Mean_3),
            typeITres0.15Mean_4 = mean(isZeroTres0.15Mean_4),
            typeITres0.15Mean_5 = mean(isZeroTres0.15Mean_5),
            typeITres0.10Mean_2 = mean(isZeroTres0.10Mean_2),
            typeITres0.10Mean_3 = mean(isZeroTres0.10Mean_3),
            typeITres0.10Mean_4 = mean(isZeroTres0.10Mean_4),
            typeITres0.10Mean_5 = mean(isZeroTres0.10Mean_5),
            typeITres0.05Mean_2 = mean(isZeroTres0.05Mean_2),
            typeITres0.05Mean_3 = mean(isZeroTres0.05Mean_3),
            typeITres0.05Mean_4 = mean(isZeroTres0.05Mean_4),
            typeITres0.05Mean_5 = mean(isZeroTres0.05Mean_5),
            typeITres0Mean_5 = mean(isZeroTres0Mean_5),
            typeITres0Mean_2 = mean(isZeroTres0Mean_2),
            typeITres0Mean_3 = mean(isZeroTres0Mean_3),
            typeITres0Mean_4 = mean(isZeroTres0Mean_4),
            typeITres0Mean_5 = mean(isZeroTres0Mean_5),
            typeICI95Mean_2 = mean(isZero95CI_2 == 0), 
            typeICI95Mean_3 = mean(isZero95CI_3 == 0),
            typeICI95Mean_4 = mean(isZero95CI_4 == 0),
            typeICI95Mean_5 = mean(isZero95CI_5 == 0),
            typeICI90Mean_2 = mean(isZero90CI_2 == 0), 
            typeICI90Mean_3 = mean(isZero90CI_3 == 0),
            typeICI90Mean_4 = mean(isZero90CI_4 == 0),
            typeICI90Mean_5 = mean(isZero90CI_5 == 0),
            typeICI80Mean_2 = mean(isZero80CI_2 == 0), 
            typeICI80Mean_3 = mean(isZero80CI_3 == 0),
            typeICI80Mean_4 = mean(isZero80CI_4 == 0),
            typeICI80Mean_5 = mean(isZero80CI_5 == 0),
            typeICI50Mean_2 = mean(isZero50CI_2 == 0), 
            typeICI50Mean_3 = mean(isZero50CI_3 == 0),
            typeICI50Mean_4 = mean(isZero50CI_4 == 0),
            typeICI50Mean_5 = mean(isZero50CI_5 == 0),
        N = mean(N),
        cross = mean(cross),
        sigmaSqu = mean(sigmaSqu))
TypeISVNP
```

## Power

```{r, echo = F, include = F}
# For Tresholdvariables: 1 = nonZero, 0 = zero
# For CI variables: 0 = nonZero, 1 = zero
PowerSVNP <- 
 resultsSVNP %>% 
  group_by(N, sigmaSqu, cross) %>% 
  summarise(powerTres0.15Mean_1 = mean(isZeroTres0.15Mean_1), 
            powerTres0.15Mean_6 = mean(isZeroTres0.15Mean_6), 
            powerTres0.10Mean_1 = mean(isZeroTres0.10Mean_1), 
            powerTres0.10Mean_6 = mean(isZeroTres0.10Mean_6), 
            powerTres0.05Mean_1 = mean(isZeroTres0.05Mean_1), 
            powerTres0.05Mean_6 = mean(isZeroTres0.05Mean_6),
            powerTres0Mean_1 = mean(isZeroTres0Mean_1), 
            powerTres0Mean_6 = mean(isZeroTres0Mean_6),
            powerCI95Mean_1 = mean(isZero95CI_1 == 0),
            powerCI95Mean_6 = mean(isZero95CI_6 == 0),
            powerCI90Mean_1 = mean(isZero90CI_1 == 0),
            powerCI90Mean_6 = mean(isZero90CI_6 == 0),
            powerCI80Mean_1 = mean(isZero80CI_1 == 0),
            powerCI80Mean_6 = mean(isZero80CI_6 == 0),
            powerCI50Mean_1 = mean(isZero50CI_1 == 0),
            powerCI50Mean_6 = mean(isZero50CI_6 == 0),
        N = mean(N),
        cross = mean(cross),
        sigmaSqu = mean(sigmaSqu) 
        #,X2.5._1 = mean(X2.5._1),
        #X97.5._1 = mean(X97.5._1)
  )
PowerSVNP
```

# Plots

```{r, include=F, echo=F}
AvgTypeIAndPower <- 
TypeISVNP %>% 
  left_join(PowerSVNP, by = c("N", "sigmaSqu", "cross")) %>% 
  transmute(avgPower_0.15 = (powerTres0.15Mean_1 + powerTres0.15Mean_6)/2, 
            avgPower_0.10 = (powerTres0.10Mean_1 + powerTres0.10Mean_6)/2, 
            avgPower_0.05 = (powerTres0.05Mean_1 + powerTres0.05Mean_6)/2, 
            avgPower_0 = (powerTres0Mean_1 + powerTres0Mean_6)/2, 
            avgPower_95 = (powerCI95Mean_1 + powerCI95Mean_6)/2, 
            avgPower_90 = (powerCI90Mean_1 + powerCI90Mean_6)/2, 
            avgPower_80 = (powerCI80Mean_1 + powerCI80Mean_6)/2, 
            avgPower_50 = (powerCI50Mean_1 + powerCI50Mean_6)/2, 
            avgTypeI_0.15 = (typeITres0.15Mean_2 + typeITres0.15Mean_3 + typeITres0.15Mean_4 + typeITres0.15Mean_5)/ 4,
            avgTypeI_0.10 = (typeITres0.10Mean_2 + typeITres0.10Mean_3 + typeITres0.10Mean_4 + typeITres0.10Mean_5)/ 4,
            avgTypeI_0.05 = (typeITres0.05Mean_2 + typeITres0.05Mean_3 + typeITres0.05Mean_4 + typeITres0.05Mean_5)/ 4,
            avgTypeI_0 = (typeITres0Mean_2 + typeITres0Mean_3 + typeITres0Mean_4 + typeITres0Mean_5)/ 4,
            avgTypeI_95 = (typeICI95Mean_2 + typeICI95Mean_3 + typeICI95Mean_4 + typeICI95Mean_5) / 4,
            avgTypeI_90 = (typeICI90Mean_2 + typeICI90Mean_3 + typeICI90Mean_4 + typeICI90Mean_5) / 4,
            avgTypeI_80 = (typeICI80Mean_2 + typeICI80Mean_3 + typeICI80Mean_4 + typeICI80Mean_5) / 4,
            avgTypeI_50 = (typeICI50Mean_2 + typeICI50Mean_3 + typeICI50Mean_4 + typeICI50Mean_5) / 4,
            cross = cross
         ) %>% 
  select(N, sigmaSqu, cross, avgPower_0.15:avgTypeI_50) %>% 
  ungroup()
AvgTypeIAndPower
```

No recode to long to allow making nice plots inspired by Zhang et al.

```{r, echo=F, include=F}
AvgTypeIAndPowerLong <- 
AvgTypeIAndPower %>% 
  pivot_longer(cols = avgPower_0.15:avgTypeI_50, 
               names_to = "Criterion",
               names_prefix = "_") %>% 
  mutate(outcome = as.factor(ifelse(str_detect(Criterion, "Power"), "power", "typeI")),
         criterion = as.factor(str_replace_all(Criterion, c("avgPower_0.15" = "Treshold 0.15", 
                                                            "avgPower_0.10" = "Treshold 0.10", 
                                                            "avgPower_0.05" = "Treshold 0.05", 
                                                            "avgPower_0" = "Treshold 0", 
                                                            "avgPower_95" = "95% Credible Interval", 
                                                            "avgPower_90" = "90% Credible Interval",
                                                            "avgPower_80" = "80% Credible Interval",
                                                            "avgPower_50" = "50% Credible Interval",
                                                            "avgTypeI_0.15" = "Treshold 0.15", 
                                                            "avgTypeI_0.10" = "Treshold 0.10", 
                                                            "avgTypeI_0.05" = "Treshold 0.05", 
                                                            "avgTypeI_0" = "Treshold 0", 
                                                            "avgTypeI_95" = "95% Credible Interval", 
                                                            "avgTypeI_90" = "90% Credible Interval",
                                                            "avgTypeI_80" = "80% Credible Interval",
                                                            "avgTypeI_50" = "50% Credible Interval" )))) %>% 
  select(N, sigmaSqu, cross, outcome, criterion, value)
```


# Power: Replicating Figure 3 Zhang et al. (p. 6)

```{r}
Power <- 
AvgTypeIAndPowerLong %>% 
  filter(outcome == "power") %>% 
  mutate(sigmaSqu = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu)),
         N = as.factor(paste0("N = ", N))) %>% 
  ggplot(mapping = aes(x = as.factor(cross), y = value, group= criterion, col = criterion, linetype = criterion))+
  geom_line()+
  geom_point(shape = 4, alpha = .8)+
  geom_hline(yintercept = 0.80, col = "red", linetype = "dashed", size = .1)+
  labs(x = "Size Cross-Loading",
       y = "Power",
       col = "Selection Criteria",
       linetype = "Selection Criteria"
       )+
  facet_grid(cols = vars(sigmaSqu),
             rows = vars(N))+
  theme_apa()+
  theme(panel.border = element_rect(fill = NA))
Power
```

## Type-I Error Rate: Replicating Figure 4 Zhang et al. (p. 7)

```{r}
# compute upper bound of acceptable type I error rate, based on Zhang ert al p. 6
upper <- 0.05 + 1.96 * sqrt(0.05 * (1-0.05)/ nIter) # 0.08
TypeI <- 
AvgTypeIAndPowerLong %>% 
  filter(outcome == "typeI") %>% 
  mutate(sigmaSqu = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu)),
         N = as.factor(paste0("N = ", N))) %>% 
  ggplot(mapping = aes(x = as.factor(cross), y = value, group = criterion, col = criterion, linetype = criterion))+
  geom_line()+
  geom_point(shape = 4, alpha = .8)+
  geom_hline(yintercept = upper, col = "red", linetype = "dashed", size = .1)+
  labs(x = "Size Cross-Loading",
       y = "Type-I Error Rate",
       col = "Selection Criteria",
       linetype = "Selection Criteria"
       )+
  facet_grid(cols = vars(sigmaSqu),
             rows = vars(N))+
  theme_apa( )+
  theme(panel.border = element_rect(fill = NA))
TypeI
```

```{r}
readr::write_rds(TypeI, file = "~/1vs2StepBayesianRegSEM/Rmd/figures/typeI.Rds")
readr::write_rds(Power, file = "~/1vs2StepBayesianRegSEM/Rmd/figures/power.Rds")
```

