---
title: "Plots MSE Mean Estimates RHSP"
author: "Koch, J.M.B. (Michael)"
date: '2022-05-02'
output: html_document
---

```{r, echo=F}
knitr::opts_chunk$set(echo = F, message = F)
```


```{r, message = F, warning = F}
# load packages outside of simulation
library(papaja)
library(patchwork)
#source required functions & parameters
source('~/OneDrive/ms/thesis/R/functions.R')
source('~/OneDrive/ms/thesis/R/parameters.R')
```


```{r}
# load results  (already filtered and post-processed)
resultsRHSP <- readRDS("~/1vs2StepBayesianRegSEM/output/resultsRHSPFilter.Rds")
nrow(resultsRHSP)
```

```{r}
mseMeanRHSP <- 
 resultsRHSP %>%
    mutate(N = as.factor(paste0("N = ", N)),
         scaleGlobal = as.factor(paste0("Scale Global = ", scaleGlobal)),
         scaleLocal = as.factor(paste0("Scale Local = ", scaleLocal)),
         dfGlobal = as.factor(paste0("Df Global  = ", dfGlobal )),
         dfLocal = as.factor(paste0("Df Local = ", dfLocal)),
         scaleSlab = as.factor(paste0("Scale Slab = ", scaleSlab)),
         dfSlab = as.factor(paste0("Df Slab = ", nu))
         ) %>% 
  select(mainEstMean_1:mainEstMean_6,
        crossEstMean_1:crossEstMean_6,
        thetaEstMean_1:thetaEstMean_6,
        factCorrEstMean,
        cross,
        N, 
        pos,
        iteration,
        scaleGlobal, scaleLocal, dfGlobal, dfLocal, dfSlab, scaleSlab) %>% 
      group_by(N, cross, scaleGlobal, scaleLocal, dfGlobal, dfLocal, dfSlab, scaleSlab) %>% 
      summarise(
        mseMainMean_1 = mean((mainEstMean_1-modelPars$main[1])^2),
        mseMainMean_2 = mean((mainEstMean_2-modelPars$main[2])^2),
        mseMainMean_3 = mean((mainEstMean_3-modelPars$main[3])^2),
        mseMainMean_4 = mean((mainEstMean_4-modelPars$main[4])^2),
        mseMainMean_5 = mean((mainEstMean_5-modelPars$main[5])^2),
        mseMainMean_6 = mean((mainEstMean_6-modelPars$main[6])^2),
        mseCrossMean_1 = mean((crossEstMean_1-cross)^2),  
        mseCrossMean_2 = mean((crossEstMean_2-0)^2), 
        mseCrossMean_3 = mean((crossEstMean_3-0)^2), 
        mseCrossMean_4 = mean((crossEstMean_4-0)^2),  
        mseCrossMean_5 = mean((crossEstMean_5-0)^2), 
        mseCrossMean_6 = mean((crossEstMean_6-cross)^2),   
        mseFactCorrMean = mean((factCorrEstMean-modelPars$Psi[1, 2])^2),
        mseThetaMean_1 = mean((thetaEstMean_1-diag(modelPars$Theta)[1])^2),
        mseThetaMean_2 = mean((thetaEstMean_2-diag(modelPars$Theta)[2])^2),
        mseThetaMean_3 = mean((thetaEstMean_3-diag(modelPars$Theta)[3])^2),
        mseThetaMean_4 = mean((thetaEstMean_4-diag(modelPars$Theta)[4])^2),
        mseThetaMean_5 = mean((thetaEstMean_5-diag(modelPars$Theta)[5])^2),
        mseThetaMean_6 = mean((thetaEstMean_6-diag(modelPars$Theta)[6])^2)
      ) %>% 
  mutate_if(is.numeric, round, 5)
mseMeanRHSP
```


# Plots

