---
title: "Plots Relative Bias"
author: "Koch, J.M.B. (Michael)"
date: '2022-05-02'
output: html_document
---
```{r, echo=F}
knitr::opts_chunk$set(echo = F, message = F)
```


```{r, message = F, warning = F}
# load packages outside of simulation
library(papaja)
library(patchwork)
#source required functions & parameters
source('~/OneDrive/ms/thesis/R/functions.R')
source('~/OneDrive/ms/thesis/R/parameters.R')
```

```{r}
# load results
resultsSVNP <- read.csv("~/OneDrive/ms/thesis/output/resultsSVNP.csv", 
                        sep = " ", 
                        header = TRUE)
convSVNP <- read.csv("~/OneDrive/ms/thesis/output/convSVNP.csv",
                     sep = " ",
                     header = TRUE)
```


```{r}
resultsSVNP <- 
  resultsSVNP %>% 
  arrange(sigma, N, cross, iteration) %>% 
  mutate(sigmaSqu = sigma^2,
         biasCrossMean_1 = abs(crossEstMean_1 - cross),
         biasCrossMean_2 = abs(crossEstMean_2 - 0),
         biasCrossMean_3 = abs(crossEstMean_3 - 0),
         biasCrossMean_4 = abs(crossEstMean_4 - 0),
         biasCrossMean_5 = abs(crossEstMean_5 - 0),
         biasCrossMean_6 = abs(crossEstMean_6 - cross),
         condID = rep(1:(nrow(condPop)*nrow(condSVNP)), each = nIter) 
) 
  
```


```{r}
relBiasSVNP <- 
 resultsSVNP %>% 
      mutate(
        relBiasMainMean_1 =  abs(mainEstMean_1 - modelPars$main[1]) /modelPars$main[1],
        relBiasMainMean_2 =  abs(mainEstMean_2 - modelPars$main[2]) /modelPars$main[2],
        relBiasMainMean_3 =  abs(mainEstMean_3 - modelPars$main[3]) /modelPars$main[3],
        relBiasMainMean_4 =  abs(mainEstMean_4 - modelPars$main[4]) /modelPars$main[4],
        relBiasMainMean_5 =  abs(mainEstMean_5 - modelPars$main[5]) /modelPars$main[5],
        relBiasMainMean_6 =  abs(mainEstMean_6 - modelPars$main[6]) /modelPars$main[6],
        relBiasCrossMean_1 = abs(crossEstMean_1 - cross)/ cross,
        relBiasCrossMean_2 = abs(crossEstMean_2 - 0), # is true par 0, rel bias = bias
        relBiasCrossMean_3 = abs(crossEstMean_3 - 0), 
        relBiasCrossMean_4 = abs(crossEstMean_4 - 0), 
        relBiasCrossMean_5 = abs(crossEstMean_5 - 0),
        relBiasCrossMean_6 = abs(crossEstMean_6 - cross)/cross, 
        relBiasFactCorrEstMean = abs(factCorrEstMean - modelPars$Psi[1, 2])/modelPars$Psi[1, 2],
        relBiasThetaMean_1 =  abs(thetaEstMean_1 - diag(modelPars$Theta)[1]) / diag(modelPars$Theta)[1],
        relBiasThetaMean_2 =  abs(thetaEstMean_2 - diag(modelPars$Theta)[2]) / diag(modelPars$Theta)[2],
        relBiasThetaMean_3 =  abs(thetaEstMean_3 - diag(modelPars$Theta)[3]) / diag(modelPars$Theta)[3],
        relBiasThetaMean_4 =  abs(thetaEstMean_4 - diag(modelPars$Theta)[4]) / diag(modelPars$Theta)[4],
        relBiasThetaMean_5 =  abs(thetaEstMean_5 - diag(modelPars$Theta)[5]) / diag(modelPars$Theta)[5],
        relBiasThetaMean_6 =  abs(thetaEstMean_6 - diag(modelPars$Theta)[6]) / diag(modelPars$Theta)[6],  
        ) %>% 
      group_by(N, sigmaSqu, cross) %>% 
      summarise(
        relBiasMainMean_1 =  mean(relBiasMainMean_1),
        relBiasMainMean_2 =  mean(relBiasMainMean_2),
        relBiasMainMean_3 =  mean(relBiasMainMean_3),
        relBiasMainMean_4 =  mean(relBiasMainMean_4),
        relBiasMainMean_5 =  mean(relBiasMainMean_5),
        relBiasMainMean_6 =  mean(relBiasMainMean_6),
        relBiasCrossMean_1 = mean(relBiasCrossMean_1),
        relBiasCrossMean_2 = mean(relBiasCrossMean_2),
        relBiasCrossMean_3 = mean(relBiasCrossMean_3),
        relBiasCrossMean_4 = mean(relBiasCrossMean_4),
        relBiasCrossMean_5 = mean(relBiasCrossMean_5),
        relBiasCrossMean_6 = mean(relBiasCrossMean_6),
        relBiasFactCorrMean = mean(relBiasFactCorrEstMean),
        relBiasThetaMean_1 =  mean(relBiasThetaMean_1),
        relBiasThetaMean_2 =  mean(relBiasThetaMean_2),
        relBiasThetaMean_3 =  mean(relBiasThetaMean_3),
        relBiasThetaMean_4 =  mean(relBiasThetaMean_4),
        relBiasThetaMean_5 =  mean(relBiasThetaMean_5),
        relBiasThetaMean_6 =  mean(relBiasThetaMean_6),
        N = mean(N),
        cross = mean(cross),
        sigmaSqu = mean(sigmaSqu)
      )
relBiasSVNP

```

# Plots

### Cross-Loadings
```{r}
crossLoading1 <- 
relBiasSVNP %>% 
  select(N, relBiasCrossMean_1, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
    cross, label) %>% 
  summarise(meanRelBiasCrossMean_1 = mean(relBiasCrossMean_1)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasCrossMean_1, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(x = "Size Cross Loading",
      y = "Mean Relative Bias",
      title = "Cross-Loading 1")+
  theme_apa()
crossLoading1
```

```{r}
crossLoading2 <- 
relBiasSVNP %>% 
  select(N, relBiasCrossMean_2, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
    cross, label) %>% 
  summarise(meanRelBiasCrossMean_2 = mean(relBiasCrossMean_2)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasCrossMean_2, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(x = "Size Cross Loading",
      y = "Mean Relative Bias",
      title = "Cross-Loading 2")+
  theme_apa()
crossLoading2
```


```{r}
crossLoading3 <- 
relBiasSVNP %>% 
  select(N, relBiasCrossMean_3, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
    cross, label) %>% 
  summarise(meanRelBiasCrossMean_3 = mean(relBiasCrossMean_3)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasCrossMean_3, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(x = "Size Cross-Loading",
      y = "Mean Relative Bias",
      title = "Cross-Loading 3")+
  ylim(0, 0.5)+
  theme_apa()
crossLoading3
```

```{r}
crossLoading4 <- 
relBiasSVNP %>% 
  select(N, relBiasCrossMean_4, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
    cross, label) %>% 
  summarise(meanRelBiasCrossMean_4 = mean(relBiasCrossMean_4)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasCrossMean_4, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(x = "Size Cross-Loading",
       y = "Mean Relative Bias",
      title = "Cross-Loading 4")+
  ylim(0, 0.5)+
  theme_apa()
crossLoading4
```

```{r}
crossLoading5 <- 
relBiasSVNP %>% 
  select(N, relBiasCrossMean_5, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
    cross, label) %>% 
  summarise(meanRelBiasCrossMean_5 = mean(relBiasCrossMean_5)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasCrossMean_5, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(x = "Size Cross Loading",
       y = "Mean Relative Bias",
      title = "Cross-Loading 5")+
  ylim(0, 0.5)+
  theme_apa()
crossLoading5
```

```{r}
crossLoading6 <- 
relBiasSVNP %>% 
  select(N, relBiasCrossMean_6, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
    cross, label) %>% 
  summarise(meanRelBiasCrossMean_6 = mean(relBiasCrossMean_6)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasCrossMean_6, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(
        x = "Size Cross Loading",
       y = "Mean Relative Bias",
      title = "Cross-Loading 6")+
  ylim(0, 0.5)+
  theme_apa()
crossLoading6
```



### Factor Correlation


```{r}
factCorr <- 
relBiasSVNP %>% 
  select(N, relBiasFactCorrMean, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiasFactCorrMean = mean(relBiasFactCorrMean)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasFactCorrMean, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(x = "Size Cross Loading",
       y = "Mean Relative Bias",
      title = "Factor Correlation")+
  ylim(0, 0.5)+
  theme_apa()
factCorr
```



### Main Loadings

```{r}
mainLoading1 <- 
relBiasSVNP %>% 
  select(N, relBiasMainMean_1, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiasMainMean_1 = mean(relBiasMainMean_1)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasMainMean_1, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(x = "Size Cross-Loading",
       y = "Mean Relative Bias",
      title = "Main Loading 1")+
  ylim(0, 0.5)+
  theme_apa()
mainLoading1
```


```{r}
mainLoading2 <- 
relBiasSVNP %>% 
  select(N, relBiasMainMean_2, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiasMainMean_2 = mean(relBiasMainMean_2)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasMainMean_2, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(x = "Size Cross-Loading",
      y = "Mean Relative Bias",
      title = " Main Loading 2")+
  ylim(0, 0.5)+
  theme_apa()
mainLoading2
```

```{r}
mainLoading3 <- 
relBiasSVNP %>% 
  select(N, relBiasMainMean_3, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiasMainMean_3 = mean(relBiasMainMean_3)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasMainMean_3, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(x = "Size Cross-Loading",
      y = "Mean Relative Bias",
      title = "Main Loading 3")+
  ylim(0, 0.5)+
  theme_apa()
mainLoading3
```


```{r}
mainLoading4 <- 
relBiasSVNP %>% 
  select(N, relBiasMainMean_4, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiasMainMean_4 = mean(relBiasMainMean_4)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasMainMean_4, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(x = "Size Cross-Loading",
       y = "Mean Relative Bias",
      title = "Main Loading 4")+
  ylim(0, 0.5)+
  theme_apa()
mainLoading4
```

```{r}
mainLoading5 <- 
relBiasSVNP %>% 
  select(N, relBiasMainMean_5, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiasMainMean_5 = mean(relBiasMainMean_5)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasMainMean_5, group = label, col = label))+
  geom_point()+
  geom_line()+
  facet_wrap(~N)+
  labs(x = "Size Cross Loading",
       y = "Mean Relative Bias",
      title = " Main Loading 5")+
    ylim(0, 0.5)+
  theme_apa()
mainLoading5
```

```{r}
mainLoading6 <- 
relBiasSVNP %>% 
  select(N, relBiasMainMean_6, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiasMainMean_6 = mean(relBiasMainMean_6)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiasMainMean_6, group = label, col = label))+
  geom_point()+
  geom_line()+
  labs(x = "Size Cross Loading",
      y = "Mean Relative Bias",
      title = "Main Loading 6")+
  facet_wrap(~N)+
  ylim(0, 0.5)+
  theme_apa()
mainLoading6
```

### Residual Variances


```{r}
theta1 <- 
relBiasSVNP %>% 
  select(N, relBiasThetaMean_1, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiastheta1 = mean(relBiasThetaMean_1)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiastheta1, group = label, col = label))+
  geom_point()+
  geom_line()+
  labs(x = "Size Cross Loading",
      y = "Mean Relative Bias",
      title = "Theta 1")+
  ylim(0, 0.5)+
  facet_wrap(~N)+
  theme_apa()
theta1
```

```{r}
theta2 <- 
relBiasSVNP %>% 
  select(N, relBiasThetaMean_2, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiastheta2 = mean(relBiasThetaMean_2)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiastheta2, group = label, col = label))+
  geom_point()+
  geom_line()+
  labs(x = "Size Cross Loading",
      y = "Mean Relative Bias",
      title = "Theta 2")+
  ylim(0, 0.5)+
  facet_wrap(~N)+
  theme_apa()
theta2
```

```{r}
theta3 <- 
relBiasSVNP %>% 
  select(N, relBiasThetaMean_3, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiastheta3 = mean(relBiasThetaMean_3)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiastheta3, group = label, col = label))+
  geom_point()+
  geom_line()+
  labs(x = "Size Cross Loading",
      y = "Mean Relative Bias",
      title = "Theta 3")+
  ylim(0, 0.5)+
  facet_wrap(~N)+
  theme_apa()
theta3
```

```{r}
theta4 <- 
relBiasSVNP %>% 
  select(N, relBiasThetaMean_4, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiastheta4 = mean(relBiasThetaMean_4)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiastheta4, group = label, col = label))+
  geom_point()+
  geom_line()+
  labs(x = "Size Cross Loading",
      y = "Mean Relative Bias",
      title = "Theta 4")+
  ylim(0, 0.5)+
  facet_wrap(~N)+
  theme_apa()
theta4
```

```{r}
theta5 <- 
relBiasSVNP %>% 
  select(N, relBiasThetaMean_5, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiastheta5 = mean(relBiasThetaMean_5)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiastheta5, group = label, col = label))+
  geom_point()+
  geom_line()+
  labs(x = "Size Cross Loading",
      y = "Mean Relative Bias",
      title = "Theta 5")+
  ylim(0, 0.5)+
  facet_wrap(~N)+
  theme_apa()
theta5
```


```{r}
theta6 <- 
relBiasSVNP %>% 
  select(N, relBiasThetaMean_6, cross, sigmaSqu) %>%
  mutate(label = as.factor(paste0("\u03c3\u00B2 = ", sigmaSqu))) %>% 
  group_by(N, 
           cross, label) %>% 
  summarise(meanRelBiastheta6 = mean(relBiasThetaMean_6)) %>% 
  ggplot(aes(x = as.factor(cross), y = meanRelBiastheta6, group = label, col = label))+
  geom_point()+
  geom_line()+
  labs(x = "Size Cross Loading",
      y = "Mean Relative Bias",
      title = "Theta 6")+
  facet_wrap(~N)+
  ylim(0, 0.5)+
  theme_apa()
theta6
```

